version: '3'
services:
  portal-en-bff:
    image: 'harbor-dev.r2ai.com.cn/r2-test/portal-admin-bff:latest'
    ports:
      - '9999:8080'
    environment:
      - AUTH_SERVICE=http://192.168.0.160:8088
      - PAY_SERVICE=http://192.168.0.105:8090
      - PAY_BFF=http://192.168.0.105:8091
      - STRAPI_SERVICE=http://192.168.0.221:1337
      - STRAPI_URL=http://192.168.0.221:1337
      - BASIC_PRICE=199.98
      - BASIC_PRICE_YEAR=2159.78
      - ESSENTIAL_PRICE=1999.98
      - ESSENTIAL_PRICE_YEAR=21599.78
      - PORT=8080
#
#  mongo:
#    image: 'mongo:4'
#    restart: always
#


